
package org.archfirst.bfoms.interfaceout.exchange.referencedataadapter.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ReferenceDataService", targetNamespace = "http://archfirst.org/bfexch/referencedataservice.wsdl", wsdlLocation = "http://localhost:8080/bfexch-javaee/ReferenceDataService?wsdl")
public class ReferenceDataService
    extends Service
{

    private final static URL REFERENCEDATASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.archfirst.bfoms.interfaceout.exchange.referencedataadapter.client.ReferenceDataService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.archfirst.bfoms.interfaceout.exchange.referencedataadapter.client.ReferenceDataService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/bfexch-javaee/ReferenceDataService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/bfexch-javaee/ReferenceDataService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        REFERENCEDATASERVICE_WSDL_LOCATION = url;
    }

    public ReferenceDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReferenceDataService() {
        super(REFERENCEDATASERVICE_WSDL_LOCATION, new QName("http://archfirst.org/bfexch/referencedataservice.wsdl", "ReferenceDataService"));
    }

    /**
     * 
     * @return
     *     returns ReferenceDataWebService
     */
    @WebEndpoint(name = "ReferenceDataWebServicePort")
    public ReferenceDataWebService getReferenceDataWebServicePort() {
        return super.getPort(new QName("http://archfirst.org/bfexch/referencedataservice.wsdl", "ReferenceDataWebServicePort"), ReferenceDataWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReferenceDataWebService
     */
    @WebEndpoint(name = "ReferenceDataWebServicePort")
    public ReferenceDataWebService getReferenceDataWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://archfirst.org/bfexch/referencedataservice.wsdl", "ReferenceDataWebServicePort"), ReferenceDataWebService.class, features);
    }

}
