-- -----------------------------------------------------------------------------
-- Caution: Do not split statements on multiple lines - Seam cannot parse them.
-- Backslash as a line continuation character doesn't work either.
-- -----------------------------------------------------------------------------

set autocommit=0;

-- -----------------------------------------------------------------------------
-- Instruments
-- -----------------------------------------------------------------------------
insert into Instrument (symbol, exchange, name) values ('A',       'NYSE',    'Agilent Technologies Inc.');
insert into Instrument (symbol, exchange, name) values ('AA',      'NYSE',    'Alcoa Inc.');
insert into Instrument (symbol, exchange, name) values ('AAPL',    'NASDAQ',  'Apple Inc.');
insert into Instrument (symbol, exchange, name) values ('ABC',     'NYSE',    'AmerisourceBergen Corporation (Holding Co)');
insert into Instrument (symbol, exchange, name) values ('ABT',     'NYSE',    'Abbott Laboratories');
insert into Instrument (symbol, exchange, name) values ('ACE',     'NYSE',    'Ace Limited');
insert into Instrument (symbol, exchange, name) values ('ADBE',    'NASDAQ',  'Adobe Systems Incorporated');
insert into Instrument (symbol, exchange, name) values ('ADI',     'NYSE',    'Analog Devices Inc.');
insert into Instrument (symbol, exchange, name) values ('ADM',     'NYSE',    'Archer-Daniels-Midland Company');
insert into Instrument (symbol, exchange, name) values ('ADP',     'NASDAQ',  'Automatic Data Processing Inc.');
insert into Instrument (symbol, exchange, name) values ('ADSK',    'NASDAQ',  'Autodesk Inc.');
insert into Instrument (symbol, exchange, name) values ('AEE',     'NYSE',    'Ameren Corporation');
insert into Instrument (symbol, exchange, name) values ('AEP',     'NYSE',    'American Electric Power Company Inc.');
insert into Instrument (symbol, exchange, name) values ('AES',     'NYSE',    'The AES Corporation');
insert into Instrument (symbol, exchange, name) values ('AET',     'NYSE',    'Aetna Inc.');
insert into Instrument (symbol, exchange, name) values ('AFL',     'NYSE',    'Aflac Incorporated');
insert into Instrument (symbol, exchange, name) values ('AGN',     'NYSE',    'Allergan Inc.');
insert into Instrument (symbol, exchange, name) values ('AIG',     'NYSE',    'American International Group Inc.');
insert into Instrument (symbol, exchange, name) values ('AIV',     'NYSE',    'Apartment Investment and Management Company');
insert into Instrument (symbol, exchange, name) values ('AIZ',     'NYSE',    'Assurant Inc.');
insert into Instrument (symbol, exchange, name) values ('AKAM',    'NASDAQ',  'Akamai Technologies Inc.');
insert into Instrument (symbol, exchange, name) values ('AKS',     'NYSE',    'AK Steel Holding Corporation');
insert into Instrument (symbol, exchange, name) values ('ALL',     'NYSE',    'Allstate Corporation (The)');
insert into Instrument (symbol, exchange, name) values ('ALTR',    'NASDAQ',  'Altera Corporation');
insert into Instrument (symbol, exchange, name) values ('AMAT',    'NASDAQ',  'Applied Materials Inc.');
insert into Instrument (symbol, exchange, name) values ('AMD',     'NYSE',    'Advanced Micro Devices Inc.');
insert into Instrument (symbol, exchange, name) values ('AMGN',    'NASDAQ',  'Amgen Inc.');
insert into Instrument (symbol, exchange, name) values ('AMP',     'NYSE',    'AMERIPRISE FINANCIAL SERVICES INC.');
insert into Instrument (symbol, exchange, name) values ('AMT',     'NYSE',    'American Tower Corporation');
insert into Instrument (symbol, exchange, name) values ('AMZN',    'NASDAQ',  'Amazon.com Inc.');
insert into Instrument (symbol, exchange, name) values ('AN',      'NYSE',    'AutoNation Inc.');
insert into Instrument (symbol, exchange, name) values ('ANF',     'NYSE',    'Abercrombie & Fitch Company');
insert into Instrument (symbol, exchange, name) values ('AON',     'NYSE',    'Aon Corporation');
insert into Instrument (symbol, exchange, name) values ('APA',     'NYSE',    'Apache Corporation');
insert into Instrument (symbol, exchange, name) values ('APC',     'NYSE',    'Anadarko Petroleum Corporation');
insert into Instrument (symbol, exchange, name) values ('APD',     'NYSE',    'Air Products and Chemicals Inc.');
insert into Instrument (symbol, exchange, name) values ('APH',     'NYSE',    'Amphenol Corporation');
insert into Instrument (symbol, exchange, name) values ('APOL',    'NASDAQ',  'Apollo Group Inc.');
insert into Instrument (symbol, exchange, name) values ('ARG',     'NYSE',    'Airgas Inc.');
insert into Instrument (symbol, exchange, name) values ('ATI',     'NYSE',    'Allegheny Technologies Incorporated');
insert into Instrument (symbol, exchange, name) values ('AVB',     'NYSE',    'AvalonBay Communities Inc.');
insert into Instrument (symbol, exchange, name) values ('AVP',     'NYSE',    'Avon Products Inc.');
insert into Instrument (symbol, exchange, name) values ('AVY',     'NYSE',    'Avery Dennison Corporation');
insert into Instrument (symbol, exchange, name) values ('AXP',     'NYSE',    'American Express Company');
insert into Instrument (symbol, exchange, name) values ('AYE',     'NYSE',    'Allegheny Energy Inc.');
insert into Instrument (symbol, exchange, name) values ('AZO',     'NYSE',    'AutoZone Inc.');
insert into Instrument (symbol, exchange, name) values ('BA',      'NYSE',    'Boeing Company (The)');
insert into Instrument (symbol, exchange, name) values ('BAC',     'NYSE',    'Bank of America Corporation');
insert into Instrument (symbol, exchange, name) values ('BAX',     'NYSE',    'Baxter International Inc.');
insert into Instrument (symbol, exchange, name) values ('BBBY',    'NASDAQ',  'Bed Bath & Beyond Inc.');
insert into Instrument (symbol, exchange, name) values ('BBT',     'NYSE',    'BB&T Corporation');
insert into Instrument (symbol, exchange, name) values ('BBY',     'NYSE',    'Best Buy Co. Inc.');
insert into Instrument (symbol, exchange, name) values ('BCR',     'NYSE',    'C.R. Bard Inc.');
insert into Instrument (symbol, exchange, name) values ('BDX',     'NYSE',    'Becton Dickinson and Company');
insert into Instrument (symbol, exchange, name) values ('BEN',     'NYSE',    'Franklin Resources Inc.');
insert into Instrument (symbol, exchange, name) values ('BF.B',    'NYSE',    'Brown Forman Corporation');
insert into Instrument (symbol, exchange, name) values ('BHI',     'NYSE',    'Baker Hughes Incorporated');
insert into Instrument (symbol, exchange, name) values ('BIG',     'NYSE',    'Big Lots Inc.');
insert into Instrument (symbol, exchange, name) values ('BIIB',    'NASDAQ',  'Biogen Idec Inc');
insert into Instrument (symbol, exchange, name) values ('BK',      'NYSE',    'Bank of New York Mellon Corporation (The)');
insert into Instrument (symbol, exchange, name) values ('BLL',     'NYSE',    'Ball Corporation');
insert into Instrument (symbol, exchange, name) values ('BMC',     'NASDAQ',  'BMC Software Inc.');
insert into Instrument (symbol, exchange, name) values ('BMS',     'NYSE',    'Bemis Company Inc.');
insert into Instrument (symbol, exchange, name) values ('BMY',     'NYSE',    'Bristol-Myers Squibb Company');
insert into Instrument (symbol, exchange, name) values ('BRCM',    'NASDAQ',  'Broadcom Corporation');
insert into Instrument (symbol, exchange, name) values ('BRK.B',   'NYSE',    'Berkshire Hathaway Inc.');
insert into Instrument (symbol, exchange, name) values ('BSX',     'NYSE',    'Boston Scientific Corporation');
insert into Instrument (symbol, exchange, name) values ('BTU',     'NYSE',    'Peabody Energy Corporation');
insert into Instrument (symbol, exchange, name) values ('BXP',     'NYSE',    'Boston Properties Inc.');
insert into Instrument (symbol, exchange, name) values ('C',       'NYSE',    'Citigroup Inc.');
insert into Instrument (symbol, exchange, name) values ('CA',      'NASDAQ',  'CA Inc.');
insert into Instrument (symbol, exchange, name) values ('CAG',     'NYSE',    'ConAgra Foods Inc.');
insert into Instrument (symbol, exchange, name) values ('CAH',     'NYSE',    'Cardinal Health Inc.');
insert into Instrument (symbol, exchange, name) values ('CAM',     'NYSE',    'Cameron International Corporation');
insert into Instrument (symbol, exchange, name) values ('CAT',     'NYSE',    'Caterpillar Inc.');
insert into Instrument (symbol, exchange, name) values ('CB',      'NYSE',    'Chubb Corporation (The)');
insert into Instrument (symbol, exchange, name) values ('CBG',     'NYSE',    'CB Richard Ellis Group Inc');
insert into Instrument (symbol, exchange, name) values ('CBS',     'NYSE',    'CBS Corporation');
insert into Instrument (symbol, exchange, name) values ('CCE',     'NYSE',    'Coca-Cola Enterprises Inc.');
insert into Instrument (symbol, exchange, name) values ('CCL',     'NYSE',    'Carnival Corporation');
insert into Instrument (symbol, exchange, name) values ('CEG',     'NYSE',    'Constellation Energy Group Inc.');
insert into Instrument (symbol, exchange, name) values ('CELG',    'NASDAQ',  'Celgene Corporation');
insert into Instrument (symbol, exchange, name) values ('CEPH',    'NASDAQ',  'Cephalon Inc.');
insert into Instrument (symbol, exchange, name) values ('CERN',    'NASDAQ',  'Cerner Corporation');
insert into Instrument (symbol, exchange, name) values ('CF',      'NYSE',    'CF Industries Holdings Inc.');
insert into Instrument (symbol, exchange, name) values ('CFN',     'NYSE',    'CareFusion Corporation');
insert into Instrument (symbol, exchange, name) values ('CHK',     'NYSE',    'Chesapeake Energy Corporation');
insert into Instrument (symbol, exchange, name) values ('CHRW',    'NASDAQ',  'C.H. Robinson Worldwide Inc.');
insert into Instrument (symbol, exchange, name) values ('CI',      'NYSE',    'CIGNA Corporation');
insert into Instrument (symbol, exchange, name) values ('CINF',    'NASDAQ',  'Cincinnati Financial Corporation');
insert into Instrument (symbol, exchange, name) values ('CL',      'NYSE',    'Colgate-Palmolive Company');
insert into Instrument (symbol, exchange, name) values ('CLF',     'NYSE',    'Cliffs Natural Resources Inc.');
insert into Instrument (symbol, exchange, name) values ('CLX',     'NYSE',    'Clorox Company (The)');
insert into Instrument (symbol, exchange, name) values ('CMA',     'NYSE',    'Comerica Incorporated');
insert into Instrument (symbol, exchange, name) values ('CMCSA',   'NASDAQ',  'Comcast Corporation');
insert into Instrument (symbol, exchange, name) values ('CME',     'NASDAQ',  'CME Group Inc.');
insert into Instrument (symbol, exchange, name) values ('CMI',     'NYSE',    'Cummins Inc.');
insert into Instrument (symbol, exchange, name) values ('CMS',     'NYSE',    'CMS Energy Corporation');
insert into Instrument (symbol, exchange, name) values ('CNP',     'NYSE',    'CenterPoint Energy Inc (Holding Co)');
insert into Instrument (symbol, exchange, name) values ('CNX',     'NYSE',    'CONSOL Energy Inc.');
commit;
insert into Instrument (symbol, exchange, name) values ('COF',     'NYSE',    'Capital One Financial Corporation');
insert into Instrument (symbol, exchange, name) values ('COG',     'NYSE',    'Cabot Oil & Gas Corporation');
insert into Instrument (symbol, exchange, name) values ('COH',     'NYSE',    'Coach Inc.');
insert into Instrument (symbol, exchange, name) values ('COL',     'NYSE',    'Rockwell Collins Inc.');
insert into Instrument (symbol, exchange, name) values ('COP',     'NYSE',    'ConocoPhillips');
insert into Instrument (symbol, exchange, name) values ('COST',    'NASDAQ',  'Costco Wholesale Corporation');
insert into Instrument (symbol, exchange, name) values ('CPB',     'NYSE',    'Campbell Soup Company');
insert into Instrument (symbol, exchange, name) values ('CPWR',    'NASDAQ',  'Compuware Corporation');
insert into Instrument (symbol, exchange, name) values ('CRM',     'NYSE',    'Salesforce.com Inc');
insert into Instrument (symbol, exchange, name) values ('CSC',     'NYSE',    'Computer Sciences Corporation');
insert into Instrument (symbol, exchange, name) values ('CSCO',    'NASDAQ',  'Cisco Systems Inc.');
insert into Instrument (symbol, exchange, name) values ('CSX',     'NYSE',    'CSX Corporation');
insert into Instrument (symbol, exchange, name) values ('CTAS',    'NASDAQ',  'Cintas Corporation');
insert into Instrument (symbol, exchange, name) values ('CTL',     'NYSE',    'CenturyLink Inc.');
insert into Instrument (symbol, exchange, name) values ('CTSH',    'NASDAQ',  'Cognizant Technology Solutions Corporation');
insert into Instrument (symbol, exchange, name) values ('CTXS',    'NASDAQ',  'Citrix Systems Inc.');
insert into Instrument (symbol, exchange, name) values ('CVC',     'NYSE',    'Cablevision Systems Corporation');
insert into Instrument (symbol, exchange, name) values ('CVH',     'NYSE',    'Coventry Health Care Inc.');
insert into Instrument (symbol, exchange, name) values ('CVS',     'NYSE',    'CVS Corporation');
insert into Instrument (symbol, exchange, name) values ('CVX',     'NYSE',    'Chevron Corporation');
insert into Instrument (symbol, exchange, name) values ('D',       'NYSE',    'Dominion Resources Inc.');
insert into Instrument (symbol, exchange, name) values ('DD',      'NYSE',    'E.I. du Pont de Nemours and Company');
insert into Instrument (symbol, exchange, name) values ('DE',      'NYSE',    'Deere & Company');
insert into Instrument (symbol, exchange, name) values ('DELL',    'NASDAQ',  'Dell Inc.');
insert into Instrument (symbol, exchange, name) values ('DF',      'NYSE',    'Dean Foods Company');
insert into Instrument (symbol, exchange, name) values ('DFS',     'NYSE',    'Discover Financial Services');
insert into Instrument (symbol, exchange, name) values ('DGX',     'NYSE',    'Quest Diagnostics Incorporated');
insert into Instrument (symbol, exchange, name) values ('DHI',     'NYSE',    'D.R. Horton Inc.');
insert into Instrument (symbol, exchange, name) values ('DHR',     'NYSE',    'Danaher Corporation');
insert into Instrument (symbol, exchange, name) values ('DIS',     'NYSE',    'Walt Disney Company (The)');
insert into Instrument (symbol, exchange, name) values ('DISCA',   'NASDAQ',  'Discovery Communications Inc');
insert into Instrument (symbol, exchange, name) values ('DNB',     'NYSE',    'Dun & Bradstreet Corporation (The)');
insert into Instrument (symbol, exchange, name) values ('DNR',     'NYSE',    'Denbury Resources Inc. (Holding Company)');
insert into Instrument (symbol, exchange, name) values ('DO',      'NYSE',    'Diamond Offshore Drilling Inc.');
insert into Instrument (symbol, exchange, name) values ('DOV',     'NYSE',    'Dover Corporation');
insert into Instrument (symbol, exchange, name) values ('DOW',     'NYSE',    'Dow Chemical Company (The)');
insert into Instrument (symbol, exchange, name) values ('DPS',     'NYSE',    'Dr Pepper Snapple Group Inc');
insert into Instrument (symbol, exchange, name) values ('DRI',     'NYSE',    'Darden Restaurants Inc.');
insert into Instrument (symbol, exchange, name) values ('DTE',     'NYSE',    'DTE Energy Company');
insert into Instrument (symbol, exchange, name) values ('DTV',     'NASDAQ',  'DIRECTV');
insert into Instrument (symbol, exchange, name) values ('DUK',     'NYSE',    'Duke Energy Corporation');
insert into Instrument (symbol, exchange, name) values ('DV',      'NYSE',    'DeVry Inc.');
insert into Instrument (symbol, exchange, name) values ('DVA',     'NYSE',    'DaVita Inc.');
insert into Instrument (symbol, exchange, name) values ('DVN',     'NYSE',    'Devon Energy Corporation');
insert into Instrument (symbol, exchange, name) values ('EBAY',    'NASDAQ',  'eBay Inc.');
insert into Instrument (symbol, exchange, name) values ('ECL',     'NYSE',    'Ecolab Inc.');
insert into Instrument (symbol, exchange, name) values ('ED',      'NYSE',    'Consolidated Edison Company of New York Inc.');
insert into Instrument (symbol, exchange, name) values ('EFX',     'NYSE',    'Equifax Inc.');
insert into Instrument (symbol, exchange, name) values ('EIX',     'NYSE',    'Edison International');
insert into Instrument (symbol, exchange, name) values ('EL',      'NYSE',    'Estee Lauder Companies Inc. (The)');
insert into Instrument (symbol, exchange, name) values ('EMC',     'NYSE',    'EMC Corporation');
insert into Instrument (symbol, exchange, name) values ('EMN',     'NYSE',    'Eastman Chemical Company');
insert into Instrument (symbol, exchange, name) values ('EMR',     'NYSE',    'Emerson Electric Company');
insert into Instrument (symbol, exchange, name) values ('EOG',     'NYSE',    'EOG Resources Inc.');
insert into Instrument (symbol, exchange, name) values ('EP',      'NYSE',    'El Paso Corporation');
insert into Instrument (symbol, exchange, name) values ('EQR',     'NYSE',    'Equity Residential');
insert into Instrument (symbol, exchange, name) values ('EQT',     'NYSE',    'EQT Corporation');
insert into Instrument (symbol, exchange, name) values ('ERTS',    'NASDAQ',  'Electronic Arts Inc.');
insert into Instrument (symbol, exchange, name) values ('ESRX',    'NASDAQ',  'Express Scripts Inc.');
insert into Instrument (symbol, exchange, name) values ('ETFC',    'NASDAQ',  'E*TRADE Financial Corporation');
insert into Instrument (symbol, exchange, name) values ('ETN',     'NYSE',    'Eaton Corporation');
insert into Instrument (symbol, exchange, name) values ('ETR',     'NYSE',    'Entergy Corporation');
insert into Instrument (symbol, exchange, name) values ('EXC',     'NYSE',    'Exelon Corporation');
insert into Instrument (symbol, exchange, name) values ('EXPD',    'NASDAQ',  'Expeditors International of Washington Inc.');
insert into Instrument (symbol, exchange, name) values ('EXPE',    'NASDAQ',  'Expedia Inc.');
insert into Instrument (symbol, exchange, name) values ('F',       'NYSE',    'Ford Motor Credit Company');
insert into Instrument (symbol, exchange, name) values ('FAST',    'NASDAQ',  'Fastenal Company');
insert into Instrument (symbol, exchange, name) values ('FCX',     'NYSE',    'Freeport-McMoran Copper & Gold Inc.');
insert into Instrument (symbol, exchange, name) values ('FDO',     'NYSE',    'Family Dollar Stores Inc.');
insert into Instrument (symbol, exchange, name) values ('FDX',     'NYSE',    'FedEx Corporation');
insert into Instrument (symbol, exchange, name) values ('FE',      'NYSE',    'FirstEnergy Corporation');
insert into Instrument (symbol, exchange, name) values ('FFIV',    'NASDAQ',  'F5 Networks Inc.');
insert into Instrument (symbol, exchange, name) values ('FHN',     'NYSE',    'First Tennessee National Corporation');
insert into Instrument (symbol, exchange, name) values ('FII',     'NYSE',    'Federated Investors Inc.');
insert into Instrument (symbol, exchange, name) values ('FIS',     'NYSE',    'Fidelity National Information Services Inc.');
insert into Instrument (symbol, exchange, name) values ('FISV',    'NASDAQ',  'Fiserv Inc.');
insert into Instrument (symbol, exchange, name) values ('FITB',    'NASDAQ',  'Fifth Third Bancorp');
insert into Instrument (symbol, exchange, name) values ('FLIR',    'NASDAQ',  'FLIR Systems Inc.');
insert into Instrument (symbol, exchange, name) values ('FLR',     'NYSE',    'Fluor Corporation');
insert into Instrument (symbol, exchange, name) values ('FLS',     'NYSE',    'Flowserve Corporation');
insert into Instrument (symbol, exchange, name) values ('FMC',     'NYSE',    'FMC Corporation');
insert into Instrument (symbol, exchange, name) values ('FO',      'NYSE',    'Fortune Brands Inc.');
insert into Instrument (symbol, exchange, name) values ('FRX',     'NYSE',    'Forest Laboratories Inc.');
insert into Instrument (symbol, exchange, name) values ('FSLR',    'NASDAQ',  'First Solar Inc.');
insert into Instrument (symbol, exchange, name) values ('FTI',     'NYSE',    'FMC Technologies Inc.');
insert into Instrument (symbol, exchange, name) values ('FTR',     'NYSE',    'Frontier Communications Company');
insert into Instrument (symbol, exchange, name) values ('GAS',     'NYSE',    'Nicor Inc.');
insert into Instrument (symbol, exchange, name) values ('GCI',     'NYSE',    'Gannett Co. Inc.');
insert into Instrument (symbol, exchange, name) values ('GD',      'NYSE',    'General Dynamics Corporation');
insert into Instrument (symbol, exchange, name) values ('GE',      'NYSE',    'General Electric Company');
insert into Instrument (symbol, exchange, name) values ('GENZ',    'NASDAQ',  'Genzyme Corporation');
insert into Instrument (symbol, exchange, name) values ('GILD',    'NASDAQ',  'Gilead Sciences Inc.');
insert into Instrument (symbol, exchange, name) values ('GIS',     'NYSE',    'General Mills Inc.');
insert into Instrument (symbol, exchange, name) values ('GLW',     'NYSE',    'Corning Incorporated');
insert into Instrument (symbol, exchange, name) values ('GME',     'NYSE',    'Gamestop Corporation');
insert into Instrument (symbol, exchange, name) values ('GNW',     'NYSE',    'Genworth Financial Inc');
insert into Instrument (symbol, exchange, name) values ('GOOG',    'NASDAQ',  'Google Inc.');
insert into Instrument (symbol, exchange, name) values ('GPC',     'NYSE',    'Genuine Parts Company');
insert into Instrument (symbol, exchange, name) values ('GPS',     'NYSE',    'Gap Inc. (The)');
insert into Instrument (symbol, exchange, name) values ('GR',      'NYSE',    'Goodrich Corporation (The)');
commit;
insert into Instrument (symbol, exchange, name) values ('GS',      'NYSE',    'Goldman Sachs Group Inc. (The)');
insert into Instrument (symbol, exchange, name) values ('GT',      'NYSE',    'Goodyear Tire & Rubber Company (The)');
insert into Instrument (symbol, exchange, name) values ('GWW',     'NYSE',    'W.W. Grainger Inc.');
insert into Instrument (symbol, exchange, name) values ('HAL',     'NYSE',    'Halliburton Company');
insert into Instrument (symbol, exchange, name) values ('HAR',     'NYSE',    'Harman International Industries Incorporated');
insert into Instrument (symbol, exchange, name) values ('HAS',     'NASDAQ',  'Hasbro Inc.');
insert into Instrument (symbol, exchange, name) values ('HBAN',    'NASDAQ',  'Huntington Bancshares Incorporated');
insert into Instrument (symbol, exchange, name) values ('HCBK',    'NASDAQ',  'Hudson City Bancorp Inc.');
insert into Instrument (symbol, exchange, name) values ('HCN',     'NYSE',    'Health Care REIT Inc.');
insert into Instrument (symbol, exchange, name) values ('HCP',     'NYSE',    'HCP Inc.');
insert into Instrument (symbol, exchange, name) values ('HD',      'NYSE',    'Home Depot Inc. (The)');
insert into Instrument (symbol, exchange, name) values ('HES',     'NYSE',    'Hess Corporation');
insert into Instrument (symbol, exchange, name) values ('HIG',     'NYSE',    'Hartford Financial Services Group Inc. (The)');
insert into Instrument (symbol, exchange, name) values ('HNZ',     'NYSE',    'H.J. Heinz Company');
insert into Instrument (symbol, exchange, name) values ('HOG',     'NYSE',    'Harley-Davidson Inc.');
insert into Instrument (symbol, exchange, name) values ('HON',     'NYSE',    'Honeywell International Inc.');
insert into Instrument (symbol, exchange, name) values ('HOT',     'NYSE',    'Starwood Hotels & Resorts Worldwide Inc.');
insert into Instrument (symbol, exchange, name) values ('HP',      'NYSE',    'Helmerich & Payne Inc.');
insert into Instrument (symbol, exchange, name) values ('HPQ',     'NYSE',    'Hewlett-Packard Company');
insert into Instrument (symbol, exchange, name) values ('HRB',     'NYSE',    'H&R Block Inc.');
insert into Instrument (symbol, exchange, name) values ('HRL',     'NYSE',    'Hormel Foods Corporation');
insert into Instrument (symbol, exchange, name) values ('HRS',     'NYSE',    'Harris Corporation');
insert into Instrument (symbol, exchange, name) values ('HSP',     'NYSE',    'Hospira Inc');
insert into Instrument (symbol, exchange, name) values ('HST',     'NYSE',    'Host Marriott Financial Trust');
insert into Instrument (symbol, exchange, name) values ('HSY',     'NYSE',    'Hershey Foods Corporation');
insert into Instrument (symbol, exchange, name) values ('HUM',     'NYSE',    'Humana Inc.');
insert into Instrument (symbol, exchange, name) values ('IBM',     'NYSE',    'International Business Machines Corporation');
insert into Instrument (symbol, exchange, name) values ('ICE',     'NYSE',    'IntercontinentalExchange Inc.');
insert into Instrument (symbol, exchange, name) values ('IFF',     'NYSE',    'Internationa Flavors & Fragrances Inc.');
insert into Instrument (symbol, exchange, name) values ('IGT',     'NYSE',    'International Game Technology');
insert into Instrument (symbol, exchange, name) values ('INTC',    'NASDAQ',  'Intel Corporation');
insert into Instrument (symbol, exchange, name) values ('INTU',    'NASDAQ',  'Intuit Inc.');
insert into Instrument (symbol, exchange, name) values ('IP',      'NYSE',    'International Paper Company');
insert into Instrument (symbol, exchange, name) values ('IPG',     'NYSE',    'Interpublic Group of Companies Inc. (The)');
insert into Instrument (symbol, exchange, name) values ('IR',      'NYSE',    'Ingersoll-Rand plc (Ireland)');
insert into Instrument (symbol, exchange, name) values ('IRM',     'NYSE',    'Iron Mountain Incorporated');
insert into Instrument (symbol, exchange, name) values ('ISRG',    'NASDAQ',  'Intuitive Surgical Inc.');
insert into Instrument (symbol, exchange, name) values ('ITT',     'NYSE',    'ITT Industries Inc.');
insert into Instrument (symbol, exchange, name) values ('ITW',     'NYSE',    'Illinois Tool Works Inc.');
insert into Instrument (symbol, exchange, name) values ('IVZ',     'NYSE',    'Invesco Plc');
insert into Instrument (symbol, exchange, name) values ('JBL',     'NYSE',    'Jabil Circuit Inc.');
insert into Instrument (symbol, exchange, name) values ('JCI',     'NYSE',    'Johnson Controls Inc.');
insert into Instrument (symbol, exchange, name) values ('JCP',     'NYSE',    'J.C. Penney Company Inc. Holding Company');
insert into Instrument (symbol, exchange, name) values ('JDSU',    'NASDAQ',  'JDS Uniphase Corporation');
insert into Instrument (symbol, exchange, name) values ('JEC',     'NYSE',    'Jacobs Engineering Group Inc.');
insert into Instrument (symbol, exchange, name) values ('JNJ',     'NYSE',    'Johnson & Johnson');
insert into Instrument (symbol, exchange, name) values ('JNPR',    'NYSE',    'Juniper Networks Inc.');
insert into Instrument (symbol, exchange, name) values ('JNS',     'NYSE',    'Janus Capital Group Inc');
insert into Instrument (symbol, exchange, name) values ('JPM',     'NYSE',    'J P Morgan Chase & Co');
insert into Instrument (symbol, exchange, name) values ('JWN',     'NYSE',    'Nordstrom Inc.');
insert into Instrument (symbol, exchange, name) values ('K',       'NYSE',    'Kellogg Company');
insert into Instrument (symbol, exchange, name) values ('KEY',     'NYSE',    'KeyCorp');
insert into Instrument (symbol, exchange, name) values ('KFT',     'NYSE',    'Kraft Foods Inc.');
insert into Instrument (symbol, exchange, name) values ('KIM',     'NYSE',    'Kimco Realty Corporation');
insert into Instrument (symbol, exchange, name) values ('KLAC',    'NASDAQ',  'KLA-Tencor Corporation');
insert into Instrument (symbol, exchange, name) values ('KMB',     'NYSE',    'Kimberly-Clark Corporation');
insert into Instrument (symbol, exchange, name) values ('KMX',     'NYSE',    'CarMax Inc');
insert into Instrument (symbol, exchange, name) values ('KO',      'NYSE',    'Coca-Cola Company (The)');
insert into Instrument (symbol, exchange, name) values ('KR',      'NYSE',    'Kroger Company (The)');
insert into Instrument (symbol, exchange, name) values ('KSS',     'NYSE',    'Kohl\'s Corporation');
insert into Instrument (symbol, exchange, name) values ('L',       'NYSE',    'Loews Corporation');
insert into Instrument (symbol, exchange, name) values ('LEG',     'NYSE',    'Leggett & Platt Incorporated');
insert into Instrument (symbol, exchange, name) values ('LEN',     'NYSE',    'Lennar Corporation');
insert into Instrument (symbol, exchange, name) values ('LH',      'NYSE',    'Laboratory Corporation of America Holdings');
insert into Instrument (symbol, exchange, name) values ('LIFE',    'NASDAQ',  'Life Technologies Corporation');
insert into Instrument (symbol, exchange, name) values ('LLL',     'NYSE',    'L-3 Communications Holdings Inc.');
insert into Instrument (symbol, exchange, name) values ('LLTC',    'NASDAQ',  'Linear Technology Corporation');
insert into Instrument (symbol, exchange, name) values ('LLY',     'NYSE',    'Eli Lilly and Company');
insert into Instrument (symbol, exchange, name) values ('LM',      'NYSE',    'Legg Mason Inc.');
insert into Instrument (symbol, exchange, name) values ('LMT',     'NYSE',    'Lockheed Martin Corporation');
insert into Instrument (symbol, exchange, name) values ('LNC',     'NYSE',    'Lincoln National Corporation');
insert into Instrument (symbol, exchange, name) values ('LO',      'NYSE',    'Lorillard Inc');
insert into Instrument (symbol, exchange, name) values ('LOW',     'NYSE',    'Lowe\'s Companies Inc.');
insert into Instrument (symbol, exchange, name) values ('LSI',     'NYSE',    'LSI Logic Corporation');
insert into Instrument (symbol, exchange, name) values ('LTD',     'NYSE',    'Limited Brands Inc.');
insert into Instrument (symbol, exchange, name) values ('LUK',     'NYSE',    'Leucadia National Corporation');
insert into Instrument (symbol, exchange, name) values ('LUV',     'NYSE',    'Southwest Airlines Company');
insert into Instrument (symbol, exchange, name) values ('LXK',     'NYSE',    'Lexmark International Inc.');
insert into Instrument (symbol, exchange, name) values ('M',       'NYSE',    'Macy\'s Inc');
insert into Instrument (symbol, exchange, name) values ('MA',      'NYSE',    'Mastercard Incorporated');
insert into Instrument (symbol, exchange, name) values ('MAR',     'NYSE',    'Marriot International');
insert into Instrument (symbol, exchange, name) values ('MAS',     'NYSE',    'Masco Corporation');
insert into Instrument (symbol, exchange, name) values ('MAT',     'NASDAQ',  'Mattel Inc.');
insert into Instrument (symbol, exchange, name) values ('MCD',     'NYSE',    'McDonald\'s Corporation');
insert into Instrument (symbol, exchange, name) values ('MCHP',    'NASDAQ',  'Microchip Technology Incorporated');
insert into Instrument (symbol, exchange, name) values ('MCK',     'NYSE',    'McKesson Corporation');
insert into Instrument (symbol, exchange, name) values ('MCO',     'NYSE',    'Moody\'s Corporation');
insert into Instrument (symbol, exchange, name) values ('MDT',     'NYSE',    'Medtronic Inc.');
insert into Instrument (symbol, exchange, name) values ('MEE',     'NYSE',    'Massey Energy Company');
insert into Instrument (symbol, exchange, name) values ('MET',     'NYSE',    'MetLife Inc.');
insert into Instrument (symbol, exchange, name) values ('MFE',     'NYSE',    'Networks Associates Inc.');
insert into Instrument (symbol, exchange, name) values ('MHP',     'NYSE',    'McGraw-Hill Companies Inc. (The)');
insert into Instrument (symbol, exchange, name) values ('MHS',     'NYSE',    'MedcoHealth Solutions Inc');
insert into Instrument (symbol, exchange, name) values ('MI',      'NYSE',    'New M&I Corporation');
insert into Instrument (symbol, exchange, name) values ('MJN',     'NYSE',    'Mead Johnson Nutrition Company');
insert into Instrument (symbol, exchange, name) values ('MKC',     'NYSE',    'McCormick & Company Incorporated');
insert into Instrument (symbol, exchange, name) values ('MMC',     'NYSE',    'Marsh & McLennan Companies Inc.');
insert into Instrument (symbol, exchange, name) values ('MMI',     'NYSE',    'Motorola Inc.');
insert into Instrument (symbol, exchange, name) values ('MMM',     'NYSE',    '3M Company');
insert into Instrument (symbol, exchange, name) values ('MO',      'NYSE',    'Altria Group');
commit;
insert into Instrument (symbol, exchange, name) values ('MOLX',    'NASDAQ',  'Molex Incorporated');
insert into Instrument (symbol, exchange, name) values ('MON',     'NYSE',    'Monsanto Company');
insert into Instrument (symbol, exchange, name) values ('MRK',     'NYSE',    'Merck & Company Inc.');
insert into Instrument (symbol, exchange, name) values ('MRO',     'NYSE',    'Marathon Oil Corporation');
insert into Instrument (symbol, exchange, name) values ('MS',      'NYSE',    'Morgan Stanley');
insert into Instrument (symbol, exchange, name) values ('MSFT',    'NASDAQ',  'Microsoft Corporation');
insert into Instrument (symbol, exchange, name) values ('MSI',     'NYSE',    'Motorola Inc.');
insert into Instrument (symbol, exchange, name) values ('MTB',     'NYSE',    'M&T Bank Corporation');
insert into Instrument (symbol, exchange, name) values ('MU',      'NASDAQ',  'Micron Technology Inc.');
insert into Instrument (symbol, exchange, name) values ('MUR',     'NYSE',    'Murphy Oil Corporation');
insert into Instrument (symbol, exchange, name) values ('MWV',     'NYSE',    'Meadwestvaco Corporation');
insert into Instrument (symbol, exchange, name) values ('MWW',     'NYSE',    'Monster Worldwide Inc.');
insert into Instrument (symbol, exchange, name) values ('MYL',     'NASDAQ',  'Mylan Inc.');
insert into Instrument (symbol, exchange, name) values ('NBL',     'NYSE',    'Noble Energy Inc.');
insert into Instrument (symbol, exchange, name) values ('NBR',     'NYSE',    'Nabors Industries Inc.');
insert into Instrument (symbol, exchange, name) values ('NDAQ',    'NASDAQ',  'The NASDAQ OMX Group Inc.');
insert into Instrument (symbol, exchange, name) values ('NE',      'NYSE',    'Noble Corporation');
insert into Instrument (symbol, exchange, name) values ('NEE',     'NYSE',    'NextEra Energy Inc.');
insert into Instrument (symbol, exchange, name) values ('NEM',     'NYSE',    'Newmont Mining Corporation (Holding Company)');
insert into Instrument (symbol, exchange, name) values ('NFLX',    'NASDAQ',  'Netflix Inc.');
insert into Instrument (symbol, exchange, name) values ('NFX',     'NYSE',    'Newfield Exploration Company');
insert into Instrument (symbol, exchange, name) values ('NI',      'NYSE',    'NiSource Inc');
insert into Instrument (symbol, exchange, name) values ('NKE',     'NYSE',    'Nike Inc.');
insert into Instrument (symbol, exchange, name) values ('NOC',     'NYSE',    'Northrop Grumman Corporation');
insert into Instrument (symbol, exchange, name) values ('NOV',     'NYSE',    'National-Oilwell Inc.');
insert into Instrument (symbol, exchange, name) values ('NOVL',    'NASDAQ',  'Novell Inc.');
insert into Instrument (symbol, exchange, name) values ('NRG',     'NYSE',    'NRG Energy Inc.');
insert into Instrument (symbol, exchange, name) values ('NSC',     'NYSE',    'Norfolk Souther Corporation');
insert into Instrument (symbol, exchange, name) values ('NSM',     'NYSE',    'National Semiconductor Corporation');
insert into Instrument (symbol, exchange, name) values ('NTAP',    'NASDAQ',  'NetApp Inc.');
insert into Instrument (symbol, exchange, name) values ('NTRS',    'NASDAQ',  'Northern Trust Corporation');
insert into Instrument (symbol, exchange, name) values ('NU',      'NYSE',    'Northeast Utilities');
insert into Instrument (symbol, exchange, name) values ('NUE',     'NYSE',    'Nucor Corporation');
insert into Instrument (symbol, exchange, name) values ('NVDA',    'NASDAQ',  'NVIDIA Corporation');
insert into Instrument (symbol, exchange, name) values ('NVLS',    'NASDAQ',  'Novellus Systems Inc.');
insert into Instrument (symbol, exchange, name) values ('NWL',     'NYSE',    'Newell Rubbermaid Inc.');
insert into Instrument (symbol, exchange, name) values ('NWSA',    'NASDAQ',  'News Corporation');
insert into Instrument (symbol, exchange, name) values ('NYX',     'NYSE',    'NYSE Euronext Inc.');
insert into Instrument (symbol, exchange, name) values ('OI',      'NYSE',    'Owens-Illinois Inc.');
insert into Instrument (symbol, exchange, name) values ('OKE',     'NYSE',    'ONEOK Inc.');
insert into Instrument (symbol, exchange, name) values ('OMC',     'NYSE',    'Omnicom Group Inc.');
insert into Instrument (symbol, exchange, name) values ('ORCL',    'NASDAQ',  'Oracle Corporation');
insert into Instrument (symbol, exchange, name) values ('ORLY',    'NASDAQ',  'O\'Reilly Automotive Inc.');
insert into Instrument (symbol, exchange, name) values ('OXY',     'NYSE',    'Occidental Petroleum Corporation');
insert into Instrument (symbol, exchange, name) values ('PAYX',    'NASDAQ',  'Paychex Inc.');
insert into Instrument (symbol, exchange, name) values ('PBCT',    'NASDAQ',  'People\'s United Financial Inc.');
insert into Instrument (symbol, exchange, name) values ('PBI',     'NYSE',    'Pitney Bowes Inc');
insert into Instrument (symbol, exchange, name) values ('PCAR',    'NASDAQ',  'PACCAR Inc.');
insert into Instrument (symbol, exchange, name) values ('PCG',     'NYSE',    'Pacific Gas & Electric Co.');
insert into Instrument (symbol, exchange, name) values ('PCL',     'NYSE',    'Plum Creek Timber Company Inc.');
insert into Instrument (symbol, exchange, name) values ('PCLN',    'NASDAQ',  'priceline.com Incorporated');
insert into Instrument (symbol, exchange, name) values ('PCP',     'NYSE',    'Precision Castparts Corporation');
insert into Instrument (symbol, exchange, name) values ('PCS',     'NYSE',    'MetroPCS Communications Inc.');
insert into Instrument (symbol, exchange, name) values ('PDCO',    'NASDAQ',  'Patterson Companies Inc.');
insert into Instrument (symbol, exchange, name) values ('PEG',     'NYSE',    'Public Service Enterprise Group Incorporated');
insert into Instrument (symbol, exchange, name) values ('PEP',     'NYSE',    'Pepsico Inc.');
insert into Instrument (symbol, exchange, name) values ('PFE',     'NYSE',    'Pfizer Inc.');
insert into Instrument (symbol, exchange, name) values ('PFG',     'NYSE',    'Principal Financial Group Inc');
insert into Instrument (symbol, exchange, name) values ('PG',      'NYSE',    'Procter & Gamble Company (The)');
insert into Instrument (symbol, exchange, name) values ('PGN',     'NYSE',    'Progress Energy Inc.');
insert into Instrument (symbol, exchange, name) values ('PGR',     'NYSE',    'Progressive Corporation (The)');
insert into Instrument (symbol, exchange, name) values ('PH',      'NYSE',    'Parker-Hannifin Corporation');
insert into Instrument (symbol, exchange, name) values ('PHM',     'NYSE',    'PulteGroup Inc.');
insert into Instrument (symbol, exchange, name) values ('PKI',     'NYSE',    'PerkinElmer Inc.');
insert into Instrument (symbol, exchange, name) values ('PLD',     'NYSE',    'ProLogis');
insert into Instrument (symbol, exchange, name) values ('PLL',     'NYSE',    'Pall Corporation');
insert into Instrument (symbol, exchange, name) values ('PM',      'NYSE',    'Philip Morris International Inc');
insert into Instrument (symbol, exchange, name) values ('PNC',     'NYSE',    'PNC Bank Corp.');
insert into Instrument (symbol, exchange, name) values ('PNW',     'NYSE',    'Pinnacle West Capital Corporation');
insert into Instrument (symbol, exchange, name) values ('POM',     'NYSE',    'Potomac Electric Power Company');
insert into Instrument (symbol, exchange, name) values ('PPG',     'NYSE',    'PPG Industries Inc.');
insert into Instrument (symbol, exchange, name) values ('PPL',     'NYSE',    'PPL Corporation');
insert into Instrument (symbol, exchange, name) values ('PRU',     'NYSE',    'Prudential Financial Inflation-Linked Retail Medium');
insert into Instrument (symbol, exchange, name) values ('PSA',     'NYSE',    'Public Storage');
insert into Instrument (symbol, exchange, name) values ('PWR',     'NYSE',    'Quanta Services Inc.');
insert into Instrument (symbol, exchange, name) values ('PX',      'NYSE',    'Praxair Inc.');
insert into Instrument (symbol, exchange, name) values ('PXD',     'NYSE',    'Pioneer Natural Resources Company');
insert into Instrument (symbol, exchange, name) values ('Q',       'NYSE',    'Qwest Communications International Inc.');
insert into Instrument (symbol, exchange, name) values ('QCOM',    'NASDAQ',  'QUALCOMM Incorporated');
insert into Instrument (symbol, exchange, name) values ('QEP',     'NYSE',    'QEP Resources Inc.');
insert into Instrument (symbol, exchange, name) values ('R',       'NYSE',    'Ryder System Inc.');
insert into Instrument (symbol, exchange, name) values ('RAI',     'NYSE',    'Reynolds American Inc');
insert into Instrument (symbol, exchange, name) values ('RDC',     'NYSE',    'Rowan Companies Inc.');
insert into Instrument (symbol, exchange, name) values ('RF',      'NYSE',    'Regions Financing Tr I');
insert into Instrument (symbol, exchange, name) values ('RHI',     'NYSE',    'Robert Half International Inc.');
insert into Instrument (symbol, exchange, name) values ('RHT',     'NYSE',    'Red Hat Inc.');
insert into Instrument (symbol, exchange, name) values ('RL',      'NYSE',    'Polo Ralph Lauren Corporation');
insert into Instrument (symbol, exchange, name) values ('ROK',     'NYSE',    'Rockwell Automation Inc');
insert into Instrument (symbol, exchange, name) values ('ROP',     'NYSE',    'Roper Industries Inc.');
insert into Instrument (symbol, exchange, name) values ('ROST',    'NASDAQ',  'Ross Stores Inc.');
insert into Instrument (symbol, exchange, name) values ('RRC',     'NYSE',    'Range Resources Corporation');
insert into Instrument (symbol, exchange, name) values ('RRD',     'NASDAQ',  'R.R. Donnelley & Sons Company');
insert into Instrument (symbol, exchange, name) values ('RSG',     'NYSE',    'Republic Services Inc.');
insert into Instrument (symbol, exchange, name) values ('RSH',     'NYSE',    'Radioshack Corporation');
insert into Instrument (symbol, exchange, name) values ('RTN',     'NYSE',    'Raytheon Company');
insert into Instrument (symbol, exchange, name) values ('S',       'NYSE',    'Sprint  Nextel Corporation');
insert into Instrument (symbol, exchange, name) values ('SAI',     'NYSE',    'SAIC Inc');
insert into Instrument (symbol, exchange, name) values ('SBUX',    'NASDAQ',  'Starbucks Corporation');
insert into Instrument (symbol, exchange, name) values ('SCG',     'NYSE',    'Scana Corporation');
insert into Instrument (symbol, exchange, name) values ('SCHW',    'NYSE',    'The Charles Schwab Corporation');
commit;
insert into Instrument (symbol, exchange, name) values ('SE',      'NYSE',    'Spectra Energy Corp');
insert into Instrument (symbol, exchange, name) values ('SEE',     'NYSE',    'Sealed Air Corporation');
insert into Instrument (symbol, exchange, name) values ('SHLD',    'NASDAQ',  'Sears Holdings Corporation');
insert into Instrument (symbol, exchange, name) values ('SHW',     'NYSE',    'Sherwin-Williams Company (The)');
insert into Instrument (symbol, exchange, name) values ('SIAL',    'NASDAQ',  'Sigma-Aldrich Corporation');
insert into Instrument (symbol, exchange, name) values ('SJM',     'NYSE',    'J.M. Smucker Company (The)');
insert into Instrument (symbol, exchange, name) values ('SLB',     'NYSE',    'Schlumberger N.V.');
insert into Instrument (symbol, exchange, name) values ('SLE',     'NYSE',    'Sara Lee Corporation');
insert into Instrument (symbol, exchange, name) values ('SLM',     'NYSE',    'SLM Corporation');
insert into Instrument (symbol, exchange, name) values ('SNA',     'NYSE',    'Snap-On Incorporated');
insert into Instrument (symbol, exchange, name) values ('SNDK',    'NASDAQ',  'SanDisk Corporation');
insert into Instrument (symbol, exchange, name) values ('SNI',     'NYSE',    'Scripps Networks Interactive Inc');
insert into Instrument (symbol, exchange, name) values ('SO',      'NYSE',    'Southern Company (The)');
insert into Instrument (symbol, exchange, name) values ('SPG',     'NYSE',    'Simon Property Group Inc.');
insert into Instrument (symbol, exchange, name) values ('SPLS',    'NASDAQ',  'Staples Inc.');
insert into Instrument (symbol, exchange, name) values ('SRCL',    'NASDAQ',  'Stericycle Inc.');
insert into Instrument (symbol, exchange, name) values ('SRE',     'NYSE',    'Sempra Energy');
insert into Instrument (symbol, exchange, name) values ('STI',     'NYSE',    'SunTrust Banks Inc.');
insert into Instrument (symbol, exchange, name) values ('STJ',     'NYSE',    'St. Jude Medical Inc.');
insert into Instrument (symbol, exchange, name) values ('STT',     'NYSE',    'State Street Corp');
insert into Instrument (symbol, exchange, name) values ('STZ',     'NYSE',    'Constellation Brands Inc');
insert into Instrument (symbol, exchange, name) values ('SUN',     'NYSE',    'Sunoco Inc.');
insert into Instrument (symbol, exchange, name) values ('SVU',     'NYSE',    'SuperValu Inc.');
insert into Instrument (symbol, exchange, name) values ('SWK',     'NYSE',    'Stanley Black & Decker Inc');
insert into Instrument (symbol, exchange, name) values ('SWN',     'NYSE',    'Southwestern Energy Company');
insert into Instrument (symbol, exchange, name) values ('SWY',     'NYSE',    'Safeway Inc.');
insert into Instrument (symbol, exchange, name) values ('SYK',     'NYSE',    'Stryker Corporation');
insert into Instrument (symbol, exchange, name) values ('SYMC',    'NASDAQ',  'Symantec Corporation');
insert into Instrument (symbol, exchange, name) values ('SYY',     'NYSE',    'Sysco Corporation');
insert into Instrument (symbol, exchange, name) values ('T',       'NYSE',    'AT&T Inc.');
insert into Instrument (symbol, exchange, name) values ('TAP',     'NYSE',    'Molson Coors Brewing  Company');
insert into Instrument (symbol, exchange, name) values ('TDC',     'NYSE',    'Teradata Corporation');
insert into Instrument (symbol, exchange, name) values ('TE',      'NYSE',    'TECO Energy Inc.');
insert into Instrument (symbol, exchange, name) values ('TEG',     'NYSE',    'Integrys Energy Group');
insert into Instrument (symbol, exchange, name) values ('TER',     'NYSE',    'Teradyne Inc.');
insert into Instrument (symbol, exchange, name) values ('TGT',     'NYSE',    'Target Corporation');
insert into Instrument (symbol, exchange, name) values ('THC',     'NYSE',    'Tenet Healthcare Corporation');
insert into Instrument (symbol, exchange, name) values ('TIE',     'NYSE',    'Titanium Metals Corporation');
insert into Instrument (symbol, exchange, name) values ('TIF',     'NYSE',    'Tiffany & Co.');
insert into Instrument (symbol, exchange, name) values ('TJX',     'NYSE',    'TJX Companies Inc. (The)');
insert into Instrument (symbol, exchange, name) values ('TLAB',    'NASDAQ',  'Tellabs Inc.');
insert into Instrument (symbol, exchange, name) values ('TMK',     'NYSE',    'Torchmark Corporation');
insert into Instrument (symbol, exchange, name) values ('TMO',     'NYSE',    'Thermo Fisher Scientific Inc');
insert into Instrument (symbol, exchange, name) values ('TROW',    'NASDAQ',  'T. Rowe Price Group Inc.');
insert into Instrument (symbol, exchange, name) values ('TRV',     'NYSE',    'The Travelers Companies Inc');
insert into Instrument (symbol, exchange, name) values ('TSN',     'NYSE',    'Tyson Foods Inc.');
insert into Instrument (symbol, exchange, name) values ('TSO',     'NYSE',    'Tesoro Petroleum Corporation');
insert into Instrument (symbol, exchange, name) values ('TSS',     'NYSE',    'Total System Services Inc.');
insert into Instrument (symbol, exchange, name) values ('TWC',     'NYSE',    'Time Warner Cable Inc');
insert into Instrument (symbol, exchange, name) values ('TWX',     'NYSE',    'Time Warner Inc.');
insert into Instrument (symbol, exchange, name) values ('TXN',     'NYSE',    'Texas Instruments Incorporated');
insert into Instrument (symbol, exchange, name) values ('TXT',     'NYSE',    'Textron Inc.');
insert into Instrument (symbol, exchange, name) values ('TYC',     'NYSE',    'Tyco International Ltd. (Switzerland)');
insert into Instrument (symbol, exchange, name) values ('UNH',     'NYSE',    'UnitedHealth Group Incorporated');
insert into Instrument (symbol, exchange, name) values ('UNM',     'NYSE',    'UnumProvident Corporation');
insert into Instrument (symbol, exchange, name) values ('UNP',     'NYSE',    'Union Pacific Corporation');
insert into Instrument (symbol, exchange, name) values ('UPS',     'NYSE',    'United Parcel Service Inc.');
insert into Instrument (symbol, exchange, name) values ('URBN',    'NASDAQ',  'Urban Outfitters Inc.');
insert into Instrument (symbol, exchange, name) values ('USB',     'NYSE',    'U.S. Bancorp');
insert into Instrument (symbol, exchange, name) values ('UTX',     'NYSE',    'United Technologies Corporation');
insert into Instrument (symbol, exchange, name) values ('V',       'NYSE',    'Visa Inc.');
insert into Instrument (symbol, exchange, name) values ('VAR',     'NYSE',    'Varian Medical Systems Inc.');
insert into Instrument (symbol, exchange, name) values ('VFC',     'NYSE',    'V.F. Corporation');
insert into Instrument (symbol, exchange, name) values ('VIA.B',   'NYSE',    'Viacom Inc.');
insert into Instrument (symbol, exchange, name) values ('VLO',     'NYSE',    'Valero Energy Corporation');
insert into Instrument (symbol, exchange, name) values ('VMC',     'NYSE',    'Vulcan Materials Company');
insert into Instrument (symbol, exchange, name) values ('VNO',     'NYSE',    'Vornado Realty Trust');
insert into Instrument (symbol, exchange, name) values ('VRSN',    'NASDAQ',  'VeriSign Inc.');
insert into Instrument (symbol, exchange, name) values ('VTR',     'NYSE',    'Ventas Inc.');
insert into Instrument (symbol, exchange, name) values ('VZ',      'NYSE',    'Verizon Communications Inc.');
insert into Instrument (symbol, exchange, name) values ('WAG',     'NYSE',    'Walgreen Company');
insert into Instrument (symbol, exchange, name) values ('WAT',     'NYSE',    'Waters Corporation');
insert into Instrument (symbol, exchange, name) values ('WDC',     'NYSE',    'Western Digital Corporation');
insert into Instrument (symbol, exchange, name) values ('WEC',     'NYSE',    'Wisconsin Energy Corporation');
insert into Instrument (symbol, exchange, name) values ('WFC',     'NYSE',    'Wells Fargo & Company');
insert into Instrument (symbol, exchange, name) values ('WFMI',    'NASDAQ',  'Whole Foods Market Inc.');
insert into Instrument (symbol, exchange, name) values ('WFR',     'NYSE',    'MEMC Electronic Materials Inc.');
insert into Instrument (symbol, exchange, name) values ('WHR',     'NYSE',    'Whirlpool Corporation');
insert into Instrument (symbol, exchange, name) values ('WIN',     'NASDAQ',  'Windstream Corporation');
insert into Instrument (symbol, exchange, name) values ('WLP',     'NYSE',    'WellPoint Health Networks Inc.');
insert into Instrument (symbol, exchange, name) values ('WM',      'NYSE',    'Waste Management Inc.');
insert into Instrument (symbol, exchange, name) values ('WMB',     'NYSE',    'Williams Companies Inc. (The)');
insert into Instrument (symbol, exchange, name) values ('WMT',     'NYSE',    'Wal-Mart Stores Inc.');
insert into Instrument (symbol, exchange, name) values ('WPI',     'NYSE',    'Watson Pharmaceuticals Inc.');
insert into Instrument (symbol, exchange, name) values ('WPO',     'NYSE',    'Washington Post Company (The)');
insert into Instrument (symbol, exchange, name) values ('WU',      'NYSE',    'Western Union Company (The)');
insert into Instrument (symbol, exchange, name) values ('WY',      'NYSE',    'Weyerhaeuser Company');
insert into Instrument (symbol, exchange, name) values ('WYN',     'NYSE',    'Wyndham Worldwide Corp');
insert into Instrument (symbol, exchange, name) values ('WYNN',    'NASDAQ',  'Wynn Resorts Limited');
insert into Instrument (symbol, exchange, name) values ('X',       'NYSE',    'United States Steel Corporation');
insert into Instrument (symbol, exchange, name) values ('XEL',     'NYSE',    'Xcel Energy Inc.');
insert into Instrument (symbol, exchange, name) values ('XL',      'NYSE',    'XL Company Switzerland GmbH (Switzerland)');
insert into Instrument (symbol, exchange, name) values ('XLNX',    'NASDAQ',  'Xilinx Inc.');
insert into Instrument (symbol, exchange, name) values ('XOM',     'NYSE',    'Exxon Mobil Corporation');
insert into Instrument (symbol, exchange, name) values ('XRAY',    'NASDAQ',  'DENTSPLY International Inc.');
insert into Instrument (symbol, exchange, name) values ('XRX',     'NYSE',    'Xerox Corporation');
insert into Instrument (symbol, exchange, name) values ('YHOO',    'NASDAQ',  'Yahoo! Inc.');
insert into Instrument (symbol, exchange, name) values ('YUM',     'NYSE',    'Yum! Brands Inc.');
insert into Instrument (symbol, exchange, name) values ('ZION',    'NASDAQ',  'Zions Bancorporation');
insert into Instrument (symbol, exchange, name) values ('ZMH',     'NYSE',    'Zimmer Holdings Inc.');
commit;
