
package org.archfirst.bfoms.interfaceout.exchange.marketdataadapter.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MarketDataWebService", targetNamespace = "http://archfirst.org/bfexch/marketdataservice.wsdl")
public interface MarketDataWebService {


    /**
     * 
     * @param symbol
     * @return
     *     returns org.archfirst.bfoms.interfaceout.exchange.marketdataadapter.client.MarketPrice
     */
    @WebMethod(operationName = "GetMarketPrice", action = "GetMarketPrice")
    @WebResult(name = "MarketPrice", targetNamespace = "")
    @RequestWrapper(localName = "GetMarketPrice", targetNamespace = "http://archfirst.org/bfexch/marketdataservice.wsdl", className = "org.archfirst.bfoms.interfaceout.exchange.marketdataadapter.client.GetMarketPrice")
    @ResponseWrapper(localName = "GetMarketPriceResponse", targetNamespace = "http://archfirst.org/bfexch/marketdataservice.wsdl", className = "org.archfirst.bfoms.interfaceout.exchange.marketdataadapter.client.GetMarketPriceResponse")
    public MarketPrice getMarketPrice(
        @WebParam(name = "Symbol", targetNamespace = "")
        String symbol);

    /**
     * 
     * @return
     *     returns java.util.List<org.archfirst.bfoms.interfaceout.exchange.marketdataadapter.client.MarketPrice>
     */
    @WebMethod(operationName = "GetMarketPrices", action = "GetMarketPrices")
    @WebResult(name = "MarketPrice", targetNamespace = "")
    @RequestWrapper(localName = "GetMarketPrices", targetNamespace = "http://archfirst.org/bfexch/marketdataservice.wsdl", className = "org.archfirst.bfoms.interfaceout.exchange.marketdataadapter.client.GetMarketPrices")
    @ResponseWrapper(localName = "GetMarketPricesResponse", targetNamespace = "http://archfirst.org/bfexch/marketdataservice.wsdl", className = "org.archfirst.bfoms.interfaceout.exchange.marketdataadapter.client.GetMarketPricesResponse")
    public List<MarketPrice> getMarketPrices();

}
