
package org.archfirst.bfoms.interfaceout.exchange.marketdataadapter.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MarketDataService", targetNamespace = "http://archfirst.org/bfexch/marketdataservice.wsdl", wsdlLocation = "http://localhost:8080/bfexch-javaee/MarketDataService?wsdl")
public class MarketDataService
    extends Service
{

    private final static URL MARKETDATASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.archfirst.bfoms.interfaceout.exchange.marketdataadapter.client.MarketDataService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.archfirst.bfoms.interfaceout.exchange.marketdataadapter.client.MarketDataService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/bfexch-javaee/MarketDataService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/bfexch-javaee/MarketDataService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MARKETDATASERVICE_WSDL_LOCATION = url;
    }

    public MarketDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MarketDataService() {
        super(MARKETDATASERVICE_WSDL_LOCATION, new QName("http://archfirst.org/bfexch/marketdataservice.wsdl", "MarketDataService"));
    }

    /**
     * 
     * @return
     *     returns MarketDataWebService
     */
    @WebEndpoint(name = "MarketDataWebServicePort")
    public MarketDataWebService getMarketDataWebServicePort() {
        return super.getPort(new QName("http://archfirst.org/bfexch/marketdataservice.wsdl", "MarketDataWebServicePort"), MarketDataWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MarketDataWebService
     */
    @WebEndpoint(name = "MarketDataWebServicePort")
    public MarketDataWebService getMarketDataWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://archfirst.org/bfexch/marketdataservice.wsdl", "MarketDataWebServicePort"), MarketDataWebService.class, features);
    }

}
